ViewModels/AddJobViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CapstoneTranslator.Models;

namespace CapstoneTranslator.ViewModels
{
    public class AddJobViewModel
    {
        public string Name { get; set; }
        public int EmployerId { get; set; }
        public int JobId { get; set; }
        public string Description { get; set; }

        public List<Language> Languages { get; set; }

        public List<SelectListItem> Employers { get; set; }

        public AddJobViewModel(List<Employer> newEmployers, List<Language> allLanguages)
        {
            Languages = allLanguages;
            Employers = new List<SelectListItem>();

            foreach (var employer in newEmployers)
            {
                Employers.Add(
                    new SelectListItem
                    {
                        Value = employer.Id.ToString(),
                        Text = employer.Name
                    }
                ); ;
            }
        }


        public AddJobViewModel()
        {
        }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CapstoneTranslator.Data;
using CapstoneTranslator.Models;
using CapstoneTranslator.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CapstoneTranslator.Controllers
{
    public class AdminController : Controller
    {
        private LanguageDbContext context;

        public AdminController(LanguageDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            List<Job> jobs = context.Jobs.Include(j => j.Employer).ToList();

            return View(jobs);
        }

        public IActionResult AddJob()
        {
            List<Employer> newEmployers = context.Employers.ToList();
            List<Language> newLanguages = context.Languages.ToList();
            AddJobViewModel addJobViewModel = new AddJobViewModel(newEmployers, newLanguages);
            return View(addJobViewModel);
        }

        [HttpPost]
        public IActionResult ProcessAddJobForm(AddJobViewModel addJobViewModel, string[] selectedLanguages)
        {
            if (ModelState.IsValid)
            {
                Employer newEmployers = context.Employers.Find(addJobViewModel.EmployerId);
                Job job = new Job
                {
                    Name = addJobViewModel.Name,
                    EmployerId = addJobViewModel.EmployerId,
                    Employer = newEmployers
                };

                foreach (string language in selectedLanguages)
                {
                    JobLanguage jobLanguage = new JobLanguage
                    {
                        LanguageId = int.Parse(language),
                        Job = job
                    };
                    context.JobLanguages.Add(jobLanguage);
                }

                context.Jobs.Add(job);
                context.SaveChanges();
                return Redirect("/Admin/Index");
            }
            return View(addJobViewModel);
        }

        public IActionResult Detail(int id)
        {
            Job theJob = context.Jobs
                .Include(j => j.Employer)
                .Single(j => j.Id == id);

            List<JobLanguage> jobLanguages = context.JobLanguages
                .Where(js => js.JobId == id)
                .Include(js => js.Language)
                .ToList();

            JobDetailViewModel viewModel = new JobDetailViewModel(theJob, jobLanguages);
            return View(viewModel);
        }
    }
}

Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CapstoneTranslator.Models;
using CapstoneTranslator.Data;
using Microsoft.EntityFrameworkCore;
using CapstoneTranslator.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CapstoneTranslator.Controllers
{
    public class ListController : Controller
    {
        internal static Dictionary<string, string> ColumnChoices = new Dictionary<string, string>()
        {
            {"all", "All"},
            {"employer", "Employer"},
            {"language", "Language"}
        };

        internal static List<string> TableChoices = new List<string>()
        {
            "employer",
            "language"
        };

        private LanguageDbContext context;

        public ListController(LanguageDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.columns = ColumnChoices;
            ViewBag.tablechoices = TableChoices;
            ViewBag.employers = context.Employers.ToList();
            ViewBag.languages = context.Languages.ToList();
            return View();
        }

        // list jobs by column and value
        public IActionResult Jobs(string column, string value)
        {
            List<Job> jobs = new List<Job>();
            List<JobDetailViewModel> displayJobs = new List<JobDetailViewModel>();

            if (column.ToLower().Equals("all"))
            {
                jobs = context.Jobs
                    .Include(j => j.Employer)
                    .ToList();

                foreach (var job in jobs)
                {
                    List<JobLanguage> jobLanguages = context.JobLanguages
                        .Where(js => js.JobId == job.Id)
                        .Include(js => js.Language)
                        .ToList();

                    JobDetailViewModel newDisplayJob = new JobDetailViewModel(job, jobLanguages);
                    displayJobs.Add(newDisplayJob);
                }

                ViewBag.title = "All Jobs";
            }
            else
            {
                if (column == "employer")
                {
                    jobs = context.Jobs
                        .Include(j => j.Employer)
                        .Where(j => j.Employer.Name == value)
                        .ToList();

                    foreach (Job job in jobs)
                    {
                        List<JobLanguage> jobLanguages = context.JobLanguages
                        .Where(js => js.JobId == job.Id)
                        .Include(js => js.Language)
                        .ToList();

                        JobDetailViewModel newDisplayJob = new JobDetailViewModel(job, jobLanguages);
                        displayJobs.Add(newDisplayJob);
                    }
                }
                else if (column == "language")
                {
                    List<JobLanguage> jobLanguage = context.JobLanguages
                        .Where(j => j.Language.Name == value)
                        .Include(j => j.Job)
                        .ToList();

                    foreach (var job in jobLanguage)
                    {
                        Job foundJob = context.Jobs
                            .Include(j => j.Employer)
                            .Single(j => j.Id == job.JobId);

                        List<JobLanguage> displayLanguages = context.JobLanguages
                            .Where(js => js.JobId == foundJob.Id)
                            .Include(js => js.Language)
                            .ToList();

                        JobDetailViewModel newDisplayJob = new JobDetailViewModel(foundJob, displayLanguages);
                        displayJobs.Add(newDisplayJob);
                    }
                }
                ViewBag.title = "Jobs with " + ColumnChoices[column] + ": " + value;
            }
            ViewBag.jobs = displayJobs;

            return View();
        }
    }
}

Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CapstoneTranslator.Models;
using CapstoneTranslator.Data;
using Microsoft.EntityFrameworkCore;
using CapstoneTranslator.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CapstoneTranslator.Controllers
{
    public class SearchController : Controller
    {
        private LanguageDbContext context;

        public SearchController(LanguageDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.columns = ListController.ColumnChoices;
            return View();
        }

        public IActionResult Results(string searchType, string searchTerm)
        {
            List<Job> jobs;
            List<JobDetailViewModel> displayJobs = new List<JobDetailViewModel>();

            if (string.IsNullOrEmpty(searchTerm))
            {
                jobs = context.Jobs
                   .Include(j => j.Employer)
                   .ToList();

                foreach (var job in jobs)
                {
                    List<JobLanguage> jobLanguages = context.JobLanguages
                        .Where(js => js.JobId == job.Id)
                        .Include(js => js.Language)
                        .ToList();

                    JobDetailViewModel newDisplayJob = new JobDetailViewModel(job, jobLanguages);
                    displayJobs.Add(newDisplayJob);
                }
            }
            else
            {
                if (searchType == "employer")
                {
                    jobs = context.Jobs
                        .Include(j => j.Employer)
                        .Where(j => j.Employer.Name == searchTerm)
                        .ToList();

                    foreach (Job job in jobs)
                    {
                        List<JobLanguage> jobLanguages = context.JobLanguages
                        .Where(js => js.JobId == job.Id)
                        .Include(js => js.Language)
                        .ToList();

                        JobDetailViewModel newDisplayJob = new JobDetailViewModel(job, jobLanguages);
                        displayJobs.Add(newDisplayJob);
                    }

                }
                else if (searchType == "Language")
                {
                    List<JobLanguage> jobLanguages = context.JobLanguages
                        .Where(j => j.Language.Name == searchTerm)
                        .Include(j => j.Job)
                        .ToList();

                    foreach (var job in jobLanguages)
                    {
                        Job foundJob = context.Jobs
                            .Include(j => j.Employer)
                            .Single(j => j.Id == job.JobId);

                        List<JobLanguage> displayLanguages = context.JobLanguages
                            .Where(js => js.JobId == foundJob.Id)
                            .Include(js => js.Language)
                            .ToList();

                        JobDetailViewModel newDisplayJob = new JobDetailViewModel(foundJob, displayLanguages);
                        displayJobs.Add(newDisplayJob);
                    }
                }
            }

            ViewBag.columns = ListController.ColumnChoices;
            ViewBag.title = "Jobs with " + ListController.ColumnChoices[searchType] + ": " + searchTerm;
            ViewBag.jobs = displayJobs;

            return View("Index");
        }
    }
}

Views/Admin/AddJob.cshtml
@model CapstoneTranslator.ViewModels.AddJobViewModel;

    <style>
        html {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 20px;
            font: serif;
            vertical-align: baseline;
        }

        body {
            font: 80% georgia, sans-serif;
            line-height: 1;
            color: black;
            background-color: lightblue;
            /*background-image: url("https://www.vpr.org/sites/vpr/files/styles/x_large/public/201708/Languages-istock-Qvasimodo-20170803.png");*/
        }

        p {
            margin-top: 0;
            text-align: justify;
            letter-spacing: 1px;
            line-height: 1.6;
        }

        footer {
            color: black;
            background-color: whitesmoke;
        }

        #highlight {
            background-color: transparent;
            text-align: center;
            width: 100%;
        }

        h3.fontCustom {
            font: Impact, sans-serif;
            color: red;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 40%;
        }
    </style>

    <h1>Add a Job</h1>

    <form asp-controller="Admin" asp-action="ProcessAddJobForm" method="post">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name"></span>
        </div>

        <div class="form-group">
            <label asp-for="EmployerId">Employer</label>
            <select asp-for="EmployerId" asp-items="@Model.Employers"></select>
            <span asp-validation-for="Employers"></span>
            <a asp-controller="Employer" asp-action="Add">Add New Employer</a>
        </div>

        <div class="form-group">
            <label asp-for="Languages">Languages Required</label>
            @if (Model.Languages == null)
            {
                <p>No Languages yet!</p>
            }
            else
            {
                @foreach (var Language in @Model.Languages)
                {
                    <input type="checkbox" name="selectedLanguages" value="@Language.Id" />
                    <label>@Language.Name</label>
                }
            }

            <a asp-controller="Language" asp-action="Add">Add New Language</a>
            <span asp-validation-for="Languages"></span>
        </div>

        <input type="submit" value="Add Job" />

    </form>

Views/Admin/Detail.cshtml
@model CapstoneTranslator.ViewModels.JobDetailViewModel

    <style>
        html {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 20px;
            font: serif;
            vertical-align: baseline;
        }

        body {
            font: 80% georgia, sans-serif;
            line-height: 1;
            color: black;
            background-color: lightblue;
            /*background-image: url("https://www.vpr.org/sites/vpr/files/styles/x_large/public/201708/Languages-istock-Qvasimodo-20170803.png");*/
        }

        p {
            margin-top: 0;
            text-align: justify;
            letter-spacing: 1px;
            line-height: 1.6;
        }

        footer {
            color: black;
            background-color: whitesmoke;
        }

        #highlight {
            background-color: transparent;
            text-align: center;
            width: 100%;
        }

        h3.fontCustom {
            font: Impact, sans-serif;
            color: red;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 40%;
        }
    </style>

    <h1>@Model.Name</h1>

    <table class="table">
        <tr>
            <th>Employer</th>
            <td>@Model.EmployerName</td>
        </tr>
        <tr>
            <th>Languages</th>
            <td>@Model.LanguageText</td>
        </tr>
        <tr>
            <th>Applicants</th>
            @*<td>@Model.Name</td*@>
        </tr>

    </table>

    <a asp-controller="Language" asp-action="AddJob" asp-route-id="@Model.JobId">Add additional Languages</a>

Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Page";
}

@model List<CapstoneTranslator.Models.Job>

    <style>
        html {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 20px;
            font: serif;
            vertical-align: baseline;
        }

        body {
            font: 80% georgia, sans-serif;
            line-height: 1;
            color: black;
            background-color: lightblue;
            /*background-image: url("https://www.vpr.org/sites/vpr/files/styles/x_large/public/201708/Languages-istock-Qvasimodo-20170803.png");*/
        }

        p {
            margin-top: 0;
            text-align: justify;
            letter-spacing: 1px;
            line-height: 1.6;
        }

        footer {
            color: black;
            background-color: whitesmoke;
        }

        #highlight {
            background-color: transparent;
            text-align: center;
            width: 100%;
        }

        h3.fontCustom {
            font: Impact, sans-serif;
            color: red;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 40%;
        }
    </style>

    <div class="text-center">
        <h2 class="display-4">Admin page!</h2>
        <p><a asp-controller="Admin" asp-action="AddJob">Add Jobs</a></p>
        <p><a asp-controller="List" asp-action="Index">List Jobs</a></p>
        <p><a asp-controller="Search" asp-action="Index">Search Jobs</a></p>
    </div>

    @if (Model.Count == 0)
    {
        <p>No jobs yet!</p>
    }
    else
    {
        <table class="table">
            <tr>
                <th>Position Name</th>
                <th>Employer</th>
            </tr>
            @foreach (Job job in Model)
            {
                <tr>
                    <td><a asp-controller="Admin" asp-action="Detail" asp-route-id="@job.Id">@job.Name</a></td>
                    <td>@job.Employer.Name</td>
                </tr>
            }
        </table>
    }