Models/Employer.cs
using System;
namespace CapstoneTranslator.Models
{
    public class Employer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Pay { get; set; }
        public string Schedule { get; set; }

        public Employer(string name, string location, string pay, string schedule)
        {
            Name = name;
            Location = location;
            Pay = pay;
            Schedule = schedule;
        }


        public Employer()
        {
        }

    }
}

Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CapstoneTranslator.Data;
using CapstoneTranslator.Models;
using CapstoneTranslator.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CapstoneTranslator.Controllers
{
    public class EmployerController : Controller
    {
        // GET: /<controller>/
        private LanguageDbContext context;

        public EmployerController(LanguageDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            List<Employer> employer = context.Employers.ToList();
            return View(employer);
        }

        public IActionResult Add()
        {
            AddEmployerViewModel addEmployerViewModel = new AddEmployerViewModel();
            return View(addEmployerViewModel);
        }

        [HttpPost]
        public IActionResult ProcessAddEmployerForm(AddEmployerViewModel addEmployerViewModel)
        {
            if (ModelState.IsValid)
            {
                Employer newEmployer = new Employer
                {
                    Name = addEmployerViewModel.Name,
                    Location = addEmployerViewModel.Location,
                    Pay = addEmployerViewModel.Pay,
                    Schedule = addEmployerViewModel.Schedule
                };

                context.Employers.Add(newEmployer);
                context.SaveChanges();
                return Redirect("/Employer");
            }
            return View(addEmployerViewModel);
        }

        public IActionResult About(int id)
        {
            Job theJob = context.Jobs
               .Include(e => e.Employer)
               .Single(e => e.Id == id);

            List<JobLanguage> jobLanguages = context.JobLanguages
                .Where(et => et.JobId == id)
                .Include(et => et.Language)
                .ToList();

            JobDetailViewModel viewModel = new JobDetailViewModel(theJob, jobLanguages);
            return View(viewModel);
        }
    }
}

Views/Employer/About.cshtml
@model CapstoneTranslator.ViewModels.AddEmployerViewModel

    <style>
        html {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 20px;
            font: serif;
            vertical-align: baseline;
        }

        body {
            font: 80% georgia, sans-serif;
            line-height: 1;
            color: black;
            background-color: lightblue;
            /*background-image: url("https://www.vpr.org/sites/vpr/files/styles/x_large/public/201708/Languages-istock-Qvasimodo-20170803.png");*/
        }

        p {
            margin-top: 0;
            text-align: justify;
            letter-spacing: 1px;
            line-height: 1.6;
        }

        footer {
            color: black;
            background-color: whitesmoke;
        }

        #highlight {
            background-color: transparent;
            text-align: center;
            width: 100%;
        }

        h3.fontCustom {
            font: Impact, sans-serif;
            color: red;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 40%;
        }
    </style>

    <div>
        <h1>Employer: Name</h1>
        <p>Name: name</p>
        <p>Location: location</p>
    </div>

Views/Employer/Add.cshtml
@model CapstoneTranslator.ViewModels.AddEmployerViewModel

    <style>
        html {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 20px;
            font: serif;
            vertical-align: baseline;
        }

        body {
            font: 80% georgia, sans-serif;
            line-height: 1;
            color: black;
            background-color: lightblue;
            /*background-image: url("https://www.vpr.org/sites/vpr/files/styles/x_large/public/201708/Languages-istock-Qvasimodo-20170803.png");*/
        }

        p {
            margin-top: 0;
            text-align: justify;
            letter-spacing: 1px;
            line-height: 1.6;
        }

        footer {
            color: black;
            background-color: whitesmoke;
        }

        #highlight {
            background-color: transparent;
            text-align: center;
            width: 100%;
        }

        h3.fontCustom {
            font: Impact, sans-serif;
            color: red;
        }

        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 40%;
        }
    </style>

<h1>Add New Employer</h1>

<form asp-controller="Employer" asp-action="ProcessAddEmployerForm" method="post">
    <div class="form-group">
        <label>Employer Name</label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label>Employer Location</label>
        <input class="form-control" asp-for="Location" />
        <span asp-validation-for="Location"></span>
    </div>
    <div class="form-group">
        <label>Employer Pay</label>
        <input class="form-control" asp-for="Pay" />
        <span asp-validation-for="Pay"></span>
    </div>
    <div class="form-group">
        <label>Employer Schedule</label>
        <input class="form-control" asp-for="Schedule" />
        <span asp-validation-for="Schedule"></span>
    </div>

    <input type="submit" value="Add Employer" />
</form>

Views/Employer/Index.cshtml
@model List<CapstoneTranslator.Models.Employer>

<style>
    html {
        margin: 0;
        padding: 0;
        border: 0;
        font-size: 20px;
        font: serif;
        vertical-align: baseline;
    }

    body {
        font: 80% georgia, sans-serif;
        line-height: 1;
        color: black;
        background-color: lightblue;
        /*background-image: url("https://www.vpr.org/sites/vpr/files/styles/x_large/public/201708/Languages-istock-Qvasimodo-20170803.png");*/
    }

    p {
        margin-top: 0;
        text-align: justify;
        letter-spacing: 1px;
        line-height: 1.6;
    }

    footer {
        color: black;
        background-color: whitesmoke;
    }

    #highlight {
        background-color: transparent;
        text-align: center;
        width: 100%;
    }

    h3.fontCustom {
        font: Impact, sans-serif;
        color: red;
    }

    img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 40%;
    }
</style>

        <h1>Employers Currently Hiring</h1>

        @if (Model.Count == 0)
        {
            <p>No employers are currently hiring!</p>
        }
        else
        {
            <div>
                <ul>
                    @foreach (Employer employer in Model)
                    {
                        <li>
                            <a asp-controller="Employer" asp-action="About" asp-route-id="@employer.Id">@employer.Name</a>
                        </li>
                    }
                </ul>
            </div>
        }
   